config/routes.rb
Rails.application.routes.draw do
    root 'welcome#index'
    get 'about' => 'welcome#about'
    get '/fetch' => 'welcome#fetch', :as => 'fetch'
    
    concern :paginatable do
        get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end
    
    # user stuff
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
    resources :users, :only => [:index, :show, :edit, :update], :concerns => :paginatable
    
    resource :profile, :only => [:index, :edit, :update] do
        root 'profiles#index'
    end
    
    resources :categories
    resources :items, :concerns => :paginatable do
        resources :comments, :only => [:new, :create, :edit, :update, :destroy]
        post '/publish' => 'items#publish'
    end
    
    resources :messages, :only => [:destroy, :index] do
        collection do
            get 'refresh'
        end
    end
    
    resources :tags, :only => [:index, :show], :param => :tag, :concerns => :paginatable
    
    namespace :admin do
        root 'admin#index'
        resources :core, :only => [:edit, :update]
        resources :menus, :only => [:index, :update, :create, :new]
#        resource :icons, :only => [:index, :update, :create]
        resources :logolink, :only => [:index, :update, :create, :destroy]
    end
    
    match '*unmatched_route', :to => 'application#raise_not_found!', :via => :all
end

app/models/logolink.rb
class Logolink < ActiveRecord::Base
	validates :url, presence: true
end

app/controllers/admin/logolink_controller.rb
class Admin::LogolinkController < ApplicationController
	before_filter :authenticate_user!

	def index
		authorize! :update, ::Logolink
		@logolinks = Logolink.find_each
		@ll_new = Logolink.new
		respond_to do |format|
			format.js
			format.html
		end
	end
	
	def create
		authorize! :create, ::Logolink
		@ll_new = Logolink.new(ll_params)
		if @ll_new.save
			flash[:success] = I18n.t(:noti_created)
			redirect_to admin_logolink_index_path
		else
			flash[:error] = I18n.t(:noti_creation_failed)
			redirect_to admin_logolink_index_path
		end
	end
	
	def update
		@ll_up = Logolink.find(params[:id])
		authorize! :update, @ll_up
		if @ll_up.update(ll_params)
			flash[:success] = I18n.t(:noti_updated)
			redirect_to admin_logolink_index_path
		else
			flash[:error] = I18n.t(:noti_update_failed)
			redirect_to admin_logolink_index_path
		end
	end
	
	def destroy
		@ll_del = Logolink.find(params[:id])
		if can? :destroy, @ll_del
			@ll_del.destroy
			flash[:success] = I18n.t(:noti_deleted)
			redirect_to admin_logolink_index_path
		else
			flash[:error] = I18n.t(:noti_deletion_failed)
			redirect_to root_path
		end
	end
	
	private
		def ll_params
			params.require(:logolink).permit(:url, :css_id, :css_class, :display)
		end
end

app/helpers/admin/logolink_helper.rb
module Admin::LogolinkHelper
end

app/views/admin/logolink/_form.html.haml
= form_for ll, url: path do |f|
  .actions
    - if ll.id?
      = link_to '<i class="fa fa-times fa-lg"></i>'.html_safe, admin_logolink_path(ll),method: :delete,data: { confirm: t(:confirm_deletion) }
  - if ll.errors.any?
    #error_explanation
      %h2
        = pluralize(ll.errors.count, "error") + ' ' + t(:save_failed)
      %ul
        - ll.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label t(:ll_url)
    = f.text_field :url
  %p
    = f.label t(:ll_css_id)
    = f.text_field :css_id
  %p
    = f.label t(:ll_css_class)
    = f.text_field :css_class
  %p
    = f.label t(:ll_display)
    = f.check_box :display
  %p
    = f.submit t(:commit), id: "left"

app/views/admin/logolink/_index.html.haml
.content.menu_edit.narrow
  = render 'admin/admin/bar'
  %p.definition
    = t(:logolink_definition).html_safe
  = @logolinks.each do |ll|
    = render 'form', :ll => ll, :path => admin_logolink_path(ll)
  = render 'form', :ll => @ll_new, :path => admin_logolink_index_path

app/views/admin/logolink/index.html.haml
- cache do
  - content_for :head do
    %title= t(:admin_logolink_index_title)
= render 'index'

app/views/admin/logolink/index.js.haml
$('#yield').html('#{escape_javascript(render partial: 'index' )}');
- cache do
  var title = '#{(t :admin_logolink_index_title)}'
  history.pushState( null, title, '#{admin_logolink_index_path}' )