config/routes.rb
Rails.application.routes.draw do
    root 'welcome#index'
    get 'about' => 'welcome#about'
    get '/fetch' => 'welcome#fetch', :as => 'fetch'
    
    concern :paginatable do
        get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end
    
    # user stuff
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
    resources :users, :only => [:index, :show, :edit, :update], :concerns => :paginatable
    
    resource :profile, :only => [:index, :edit, :update] do
        root 'profiles#index'
    end
    
    resources :categories
    resources :items, :concerns => :paginatable do
        resources :comments, :only => [:new, :create, :edit, :update, :destroy]
        post '/publish' => 'items#publish'
    end
    
    resources :messages, :only => [:destroy, :index] do
        collection do
            get 'refresh'
        end
    end
    
    resources :tags, :only => [:index, :show], :param => :tag, :concerns => :paginatable
    
    namespace :admin do
        root 'admin#index'
        resources :core, :only => [:edit, :update]
        resources :menus, :only => [:index, :update, :create, :new]
#        resource :icons, :only => [:index, :update, :create]
        resources :logolink, :only => [:index, :update, :create, :destroy]
    end
    
    match '*unmatched_route', :to => 'application#raise_not_found!', :via => :all
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@page = StaticPage.first
		@links = Logolink.all
		@recent = Item.order('created_at DESC').where(:published => true, :deleted => false).limit(3)
		respond_to do |format|
			format.js
			format.html
		end
	end
	
	def about
		@page = StaticPage.second
		respond_to do |format|
			format.js
			format.html
		end
	end
	
	def fetch
		if params[:node] == '1'
			@selected = Item.order('created_at DESC').where(:published => true, :deleted => false).limit(3)
			respond_to do |format|
				format.js { render :action => "fetch_recent" }
				format.html { redirect_to(items_path) }
			end
		elsif params[:node] == '2'
			@categories = Category.all
			respond_to do |format|
				format.js { render :action => "fetch_categories" }
				format.html { redirect_to(categories_path) }
			end
		elsif params[:node] == '3'
			@tags = ActsAsTaggableOn::Tag.most_used(10)
			respond_to do |format|
				format.js { render :action => "fetch_tags" }
				format.html { redirect_to(tags_path) }
			end
		else
			
		end
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
	def cache_key_for_recent_items
    count          = Item.count
		max_updated_at = Item.where(:deleted => false, :published => true).maximum(:updated_at).try(:utc).try(:to_s, :number)
		"items/recent-#{count}-#{max_updated_at}"
	end
	
	def cache_key_for_categories
		max_updated_at = Category.maximum(:updated_at).try(:utc).try(:to_s, :number)
		"categories/all-#{max_updated_at}"
	end
end

app/views/welcome/_about.html.haml
#about.content
  %span.actions
    - if can? :update, @page
      = link_to t(:change_nav).html_safe, edit_admin_core_path(@page), :remote => true
  - cache(@page) do
    = markdown(@page.content).html_safe

app/views/welcome/_account.html.erb
<% if current_user %>
	<div class="holder">
		<div class="tools">
			<%= link_to current_user.display_name, user_path(current_user) %>
			<span class="qtab"></span>|<span class="qtab"></span>
			<%= link_to 'edit', edit_profile_path %>
			<% if can? :update, Website %>
				<span class="qtab"></span>|<span class="qtab"></span>
				<%= link_to 'admin tools', admin_root_path %>
			<% end %>
		</div>
		<div class="logout">
			<%= link_to :logout, user_session_path,method: :delete,data: { confirm: 'Are you sure?' } %>
		</div>
	</div>
<% else %>
	<div class="holder">
		<div class="login">
			<%= link_to :login, login_path %>
			<span class="tab"></span>
			<%= link_to :register, register_path %>
		</div>
	</div>
<% end %>

app/views/welcome/_index.html.haml
#main.content
  %span.actions
    - if can? :update, @page
      = link_to t(:change_nav).html_safe, edit_admin_core_path(@page), :remote => true
  - cache(@page) do
    = markdown(@page.content).html_safe
  = render 'logolinks'
= render 'recent'

app/views/welcome/_logolinks.html.haml
- cache(@links) do
  - if Core.first.show_icons?
    //:javascript
    //  $('#linkbar').find('a').each(function(i) {$(this)
    //      .css({"top":"-1em","position":"relative","opacity":"0"})
    //      .delay(i*150).animate({"opacity":"1","top":"0em"}, 250);});
    #linkbar
      - @links.each do |link|
        - if link.display?
          = link_to '', link.url, :id => link.css_id, :class => t(:logolink_class_helper, :link => link.css_class)

app/views/welcome/_recent.html.haml
.content
  - cache do
    %p.nav
      = link_to t(:recent_posts_nav).html_safe, fetch_path(:node => '1'), :remote => true, :class => "btn btn-lh btn-border-o"
      = link_to t(:all_categories_nav).html_safe, fetch_path(:node => '2'), :remote => true, :class => "btn btn-lh btn-border-o"
      = link_to t(:top_tags_nav).html_safe, fetch_path(:node => '3'), :remote => true, :class => "btn btn-lh btn-border-o"
      = link_to t(:all_posts_nav).html_safe, items_path, :remote => true, :class => "btn btn-lh btn-border-o"
  #items
    = render 'recent_block', :recent => @recent

app/views/welcome/_recent_block.html.haml
- recent.each do |item|
  %hr/
  = render 'items/single', :item => item

app/views/welcome/_tag_block.html.haml
.tags
  %br/
  - @tags.each do |tag|
    = render 'tags/single', :tag => tag

app/views/welcome/about.html.haml
- cache(@page) do
  - content_for :head do
    %title= @page.title
= render 'about'

app/views/welcome/about.js.haml
- cache(@page) do
  $('#yield').html('#{escape_javascript(render partial: 'about', locals: { page: @page } )}');
  var title = '#{@page.title}'
  history.pushState( null, title, '#{about_path}' )

app/views/welcome/fetch_categories.js.haml
- cache(cache_key_for_categories) do
  $('#items').html('#{escape_javascript(render partial: 'category_block', locals: { cat: @categories } )}');

app/views/welcome/fetch_recent.js.haml
- cache(cache_key_for_recent_items) do
  $('#items').html('#{escape_javascript(render partial: 'recent_block', locals: { recent: @selected } )}');

app/views/welcome/fetch_tags.js.haml
$('#items').html('#{escape_javascript(render partial: 'tag_block' )}');

app/views/welcome/index.html.haml
- cache(@page) do
  - content_for :head do
    %title= @page.title
= render 'index'

app/views/welcome/index.js.haml
$('#yield').html('#{escape_javascript(render partial: 'index', locals: { page: @page } )}');
- cache(@page) do
  var title = '#{@page.title}'
  history.pushState( null, title, '#{root_path}' )