config/routes.rb
Rails.application.routes.draw do
    root 'welcome#index'
    get 'about' => 'welcome#about'
    get '/fetch' => 'welcome#fetch', :as => 'fetch'
    
    concern :paginatable do
        get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end
    
    # user stuff
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
    resources :users, :only => [:index, :show, :edit, :update], :concerns => :paginatable
    
    resource :profile, :only => [:index, :edit, :update] do
        root 'profiles#index'
    end
    
    resources :categories
    resources :items, :concerns => :paginatable do
        resources :comments, :only => [:new, :create, :edit, :update, :destroy]
        post '/publish' => 'items#publish'
    end
    
    resources :messages, :only => [:destroy, :index] do
        collection do
            get 'refresh'
        end
    end
    
    resources :tags, :only => [:index, :show], :param => :tag, :concerns => :paginatable
    
    namespace :admin do
        root 'admin#index'
        resources :core, :only => [:edit, :update]
        resources :menus, :only => [:index, :update, :create, :new]
#        resource :icons, :only => [:index, :update, :create]
        resources :logolink, :only => [:index, :update, :create, :destroy]
    end
    
    match '*unmatched_route', :to => 'application#raise_not_found!', :via => :all
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
	belongs_to :menus
	validates :name, :summary, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	load_and_authorize_resource

	def index
		respond_to do |format|
			format.js
			format.html
		end
	end
	
	def show
		@posts = @category.items.where(:deleted => false, :published => true).page params[:page]
		respond_to do |format|
			format.js
			format.html
		end
	end
	
	def new
		@menu_options = Menu.all.map{|c| [ c.title, c.id ] }
		respond_to do |format|
			format.js
			format.html
		end
	end

	def edit
		@menu_options = Menu.all.map{|c| [ c.title, c.id ] }
		respond_to do |format|
			format.js
			format.html
		end
	end
 
	def create
		@menu_options = Menu.all.map{|c| [ c.title, c.id ] }
		if @category.save
			flash[:success] = I18n.t(:noti_category_created)
			redirect_to @category
		else
			flash[:error] = I18n.t(:noti_creation_failed)
			render 'new'
		end
	end
	
	def update
		@menu_options = Menu.all.map{|c| [ c.title, c.id ] }
		if @category.update(category_params)
			flash[:success] = I18n.t(:noti_category_updated)
			redirect_to @category
		else
			flash[:success] = I18n.t(:noti_update_failed)
			render 'edit'
		end
	end
	
	def destroy
		@category.destroy
		flash[:success] = I18n.t(:noti_category_deleted)
		redirect_to categories_path
	end
	
	private
		def category_params
			params.require(:category).permit(:name, :summary, :menu_id)
		end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_edit.html.haml
.content.narrow
  - cache do
    %p.definition
      = t(:change_definition).html_safe
  = render 'form'

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2
        = pluralize(@category.errors.count, "error") + ' ' + t(:save_failed)
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :name
    %br/
    = f.text_field :name
  %p
    = f.label :summary
    %br/
    = f.text_field :summary
  - if can? :update, Menu
    %p
      = f.label 'Include in menu?'
      %br/
      = f.select :menu_id, options_for_select(@menu_options, @category.menu_id)
  %p
    = f.submit t(:commit)

app/views/categories/_index.html.haml
.content.categories
  %p.definition
    = t(:index_definition).html_safe
  %hr/
  - @categories.each do |category|
    = render 'single', :category => category
  - if can? :create, @category
    .entry
      .title
        %span.actions
          = link_to t(:create_nav).html_safe, new_category_path, :remote => true
        &nbsp

app/views/categories/_new.html.haml
.content.narrow
  - cache do
    %p.definition
      = t(:creation_definition).html_safe
  = render 'form'

app/views/categories/_show.html.haml
.content.narrow
  %span.actions
    = link_to t(:index_nav).html_safe, categories_path, :remote => true
    - if can? :update, @category
      = link_to t(:change_nav).html_safe, edit_category_path(@category), :remote => true
    - if can? :create, Item
      = link_to t(:create_nav).html_safe, new_item_path, :remote => true
  -cache(@category) do
    %p.definition
      %strong= @category.name
      %br/
    %hr/
    = markdown(@category.summary).html_safe
  - @posts.each do |item|
    %hr/
    = render 'items/single', :item => item
  %hr/
  = paginate @posts, :remote => true

app/views/categories/_single.html.haml
- cache(category) do
  .entry
    .title
      = link_to category.name, category_path(category), :remote => true
      - if can? :update, category
        %span.actions
          = link_to t(:change_nav).html_safe, edit_category_path(category), :remote => true
          = link_to t(:delete_nav).html_safe, category_path(category),method: :delete,data: { confirm: t(:confirm_deletion) }

app/views/categories/edit.html.haml
- cache do
  - content_for :head do
    %title= t :edit_category_title
= render 'edit'

app/views/categories/edit.js.haml
$('#yield').html('#{escape_javascript(render partial: 'edit' )}');
- cache do
  var title = '#{t :edit_category_title}'
  history.pushState( null, title, '#{edit_category_path(params[:id])}' )

app/views/categories/index.html.haml
- cache do
  - content_for :head do
    %title= (t :category_index_title)
= render 'index'

app/views/categories/index.js.haml
$('#yield').html('#{escape_javascript(render partial: 'index' )}');
- cache do
  var title = '#{(t :category_index_title)}'
  history.pushState( null, title, '#{categories_path}' )

app/views/categories/new.html.haml
- cache do
  - content_for :head do
    %title= t :new_category_title
= render 'new'

app/views/categories/new.js.haml
$('#yield').html('#{escape_javascript(render partial: 'new' )}');
- cache do
  var title = '#{t :new_category_title}'
  history.pushState( null, title, '#{new_category_path}' )

app/views/categories/show.html.haml
- content_for :head do
  %title= t(:view_category_title, :title => @category.name)
= render 'show'

app/views/categories/show.js.haml
$('#yield').html('#{escape_javascript(render partial: 'show' )}');
var title = '#{t(:view_category_title, :title => @category.name)}'
history.pushState( null, title, '#{category_path(params[:id])}' )