config/routes.rb
Rails.application.routes.draw do
    root 'welcome#index'
    get 'about' => 'welcome#about'
    get '/fetch' => 'welcome#fetch', :as => 'fetch'
    
    concern :paginatable do
        get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end
    
    # user stuff
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
    resources :users, :only => [:index, :show, :edit, :update], :concerns => :paginatable
    
    resource :profile, :only => [:index, :edit, :update] do
        root 'profiles#index'
    end
    
    resources :categories
    resources :items, :concerns => :paginatable do
        resources :comments, :only => [:new, :create, :edit, :update, :destroy]
        post '/publish' => 'items#publish'
    end
    
    resources :messages, :only => [:destroy, :index] do
        collection do
            get 'refresh'
        end
    end
    
    resources :tags, :only => [:index, :show], :param => :tag, :concerns => :paginatable
    
    namespace :admin do
        root 'admin#index'
        resources :core, :only => [:edit, :update]
        resources :menus, :only => [:index, :update, :create, :new]
#        resource :icons, :only => [:index, :update, :create]
        resources :logolink, :only => [:index, :update, :create, :destroy]
    end
    
    match '*unmatched_route', :to => 'application#raise_not_found!', :via => :all
end

app/models/ability.rb
class Ability
	include CanCan::Ability

	def initialize(user)
		user ||= User.new # if necessary, create a guest user
		
		can :read, [Category, User]
		can :read, [Comment], :deleted => false
		can :read, [Item], :deleted => false, :published => true
		can :see, [:moderator, :editor, :author, :commenter]
		
		if user.id == nil # for guest users
			can :create, User
		else
			# these permissions are given to every user.
			can :see, [:admin]
			can :manage, User, :id => user.id
			can :timestamp, User, :id => user.id
			can :see_email, User, :id => user.id
			# now, let's see what special things we can do ...
			user.roles.each do |role|
				self.send role, user # need to pass the user object along, or things break.
			end
		end
	end
	
	# remember, the set of valid roles is defined in user.rb. Adding new ones here is necessary but not sufficient.
	private
	
	def superadmin(user)
		can :manage, :all
	end
	
	def admin(user)
		can :manage, [Comment, Item, Category, User, StaticPage, Menu]
		can :assign, [:moderator, :editor, :author, :commenter]
		can :see, [:superadmin, :admin_tools]
	end
	
	def moderator(user)
		can :manage, Comment, :deleted => false
	end
	
	def editor(user)
		can :manage, Item, :deleted => false
	end
	
	def author(user)
		can :manage, Item, :user_id => user.id, :deleted => false
	end
	
	def commenter(user)
		can :manage, Comment, :user_id => user.id, :deleted => false
	end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
	belongs_to :menus
	validates :name, :summary, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :item
	has_ancestry :orphan_strategy => :restrict
	validates :body, :item, presence: true
end

app/models/core.rb
class Core < ActiveRecord::Base
	
end

app/models/group.rb
class Group < ActiveRecord::Base
	groupify :group, members: [:users, :items], default_members: :users
	validates :title, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
	acts_as_taggable
	belongs_to :category
	belongs_to :user
	has_many :comments
	validates :title, :content, :summary, :category, :user, presence: true
	default_scope { order("created_at DESC") }
	paginates_per 10
end

app/models/logolink.rb
class Logolink < ActiveRecord::Base
	validates :url, presence: true
end

app/models/menu.rb
class Menu < ActiveRecord::Base
	has_many :categories
	validates :title, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
	has_many :categories
	validates :title, :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	# hooks
	before_create :set_defaults
	before_destroy :clean_up_possessions
	
	# setup roles using RoleModel
	include RoleModel
	roles_attribute :roles_mask
	# this is the master list of all accessible roles
	roles :superadmin, :admin, :moderator, :editor, :author, :commenter
	
	# mailboxer
	acts_as_messageable
	
	# mount uploader to manage avatars
	mount_uploader :avatar, AvatarUploader
	
	# devise
	devise :database_authenticatable, :registerable, :lockable,
		:recoverable, :rememberable, :trackable, :validatable,
		:omniauthable, :omniauth_providers => [:twitter]
		
	# relationships
	has_many :items
	has_many :comments

	# validation
	validates :password, presence: true, on: :create
	validates :email, :display_name, presence: true, on: create
	validates :email, :display_name, uniqueness: true
	validates :email, :email => {:allow_blank => true}
	validates :website, :url => {:allow_blank => true}
	
	paginates_per 10
	
	# omniauth login & registration
	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.email = auth.info.email
			user.website = auth.info.urls.Twitter
			user.biography = auth.info.description
			user.password = Devise.friendly_token[0,20]
			user.display_name = auth.info.name
			user.roles << :commenter
		end
	end
	
	# check if the user has a role
	def role?(role)
		return !!self.roles.find_by_name(role.to_s.camelize)
	end
 
	def get_user
		@current_user = current_user
	end
	
	def mailboxer_email(object)
		return self.email
	end
	
	private
	
	def email_required?
      true unless !self.provider.nil?
    end
	
	# Gives all users the default role of commenter and puts them in the registered users group
	def set_defaults
		self.roles << :commenter
		self.groups << Group.first
	end
	
	# Before a user is destroyed, clean up all of their items and comments.
	def clean_up_possessions
		# Consider changing this to just remove user ids? Or that alongside tagging them as deleted and hiding them from most users.
		self.items.each do |item|
			item.destroy
		end
		self.comments.each do |comment|
			comment.destroy
		end
	end
end

app/models/website.rb
class Website < ActiveRecord::Base
	has_many :categories
	validates :title, :content, :menu_title, presence: true
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def cache_key_for_items
    count          = Item.count
    max_updated_at = Item.maximum(:updated_at).try(:utc).try(:to_s, :number)
    page           = params[:page]
    "items/all-#{count}-#{max_updated_at}-#{page}"
  end
end

app/helpers/locks_helper.rb
module LocksHelper
end

app/helpers/tags_helper.rb
module TagsHelper
  def cache_key_for_tags
    count          = (ActsAsTaggableOn::Tag.most_used).count
    page           = params[:page]
    "tags/all-#{count}-#{page}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def cache_key_for_users
    count          = User.count
    max_updated_at = User.maximum(:updated_at).try(:utc).try(:to_s, :number)
    page           = params[:page]
    "users/all-#{count}-#{max_updated_at}-#{page}"
  end
end

app/views/admin/admin/_bar.html.haml
%div.admin-nav
  %span.link
    = link_to_if((controller_name != 'admin'), :admin_index, admin_root_path, :remote => true)
  %span.link
    = link_to_if((controller_name != 'menus'), :edit_menus, admin_menus_path, :remote => true)
  %span.link
    = link_to_if((controller_name != 'logolink'), :edit_logolinks, admin_logolink_index_path, :remote => true)

app/views/admin/admin/_index.html.haml
.content.narrow
  = render 'bar'
  %p.definition
    = t(:admin_tools_definition).html_safe
  %p
    = t(:admin_tools_message).html_safe

app/views/admin/admin/index.html.haml
- content_for :head do
  %title= t(:admin_index_title)
- cache do
  = render 'index'

app/views/admin/admin/index.js.haml
- cache do
  $('#yield').html('#{escape_javascript(render partial: 'index' )}');
  var title = '#{(t :admin_index_title)}'
  history.pushState( null, title, '#{admin_root_path}' )

app/views/admin/index.html.erb
<% content_for :head do %>
	<title>Admin Tools</title>
<% end %>

<div class="content">
	<%= render 'admin/bar' %>
	<p class="definition">
		<strong>Admin Tools</strong>
	</p>
	<p>
	Presently, all other administrator tools are accessed from the page to which they apply.
	</p>
</div>

app/views/admins/_form.html.erb
<%= form_for @page, url: admin_path do |f| %>
	<% if @page.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@page.errors.count, "error") %> prohibited your changes from being saved:
			</h2>
			<ul>
				<% @page.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>
			
	<p>	
		<%= f.label :content %><br>
		<%= f.text_area :content %>
	</p>
		
	<p>
		<%= f.submit 'preview', id: "left" %>
		<%= f.submit 'commit', id: "right" %>
	</p>
	&nbsp
<% end %>

app/views/admins/edit.html.erb
<% content_for :head do %>
	<title>Change</title>
<% end %>

<div id="content">
	<div id="definition">
		<strong>Change</strong> - <em>v</em>. To become different.
	</div>
	<%= render 'form' %>
</div>

app/views/admins/preview.html.erb
<% content_for :head do %>
	<title>Change</title>
<% end %>

<div id="content">
	<div id="definition">
		<strong>Change</strong> - <em>v</em>. To become different.
	</div>
	<%= render 'form' %>
</div>
<div id="content">
	<%= markdown(@page.content).html_safe =%>
</div>

app/views/confirmable/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/shared/_footer.html.haml
%footer
  .bottom
    %i.fa.fa-copyright>
    2015
    %span#background-attribution
      | Background derived from
      %a{:href => "https://www.flickr.com/photos/tree_leaf_clover/6250902701/", :target => "blank_"} Dmitry Kalinin
      \/
      %a{:href => "https://creativecommons.org/licenses/by/2.0/", :target => "_blank"} CC BY
  .right.tools
    - if current_user
      = link_to t(:user_nav).html_safe + ' ' + current_user.display_name, profile_path, :remote => true
      - if can? :update, Core
        = link_to t(:admin_settings_nav).html_safe, admin_root_path, :remote => true
      = link_to t(:settings_nav).html_safe, edit_profile_path, :remote => true
      = link_to t(:logout_nav).html_safe, destroy_user_session_path, method: :delete,data: { confirm: t(:confirm_logout) }
    - elsif Core.first.show_login? && (controller_name != 'sessions') && (controller_name != 'registrations')
      - cache do
        = link_to t(:oauth_twitter_nav).html_safe, user_omniauth_authorize_path(provider: 'twitter')
        = link_to t(:login_nav).html_safe, new_user_session_path
        = link_to t(:register_nav).html_safe, new_user_registration_path

app/views/shared/_menu.html.haml
- cache(cache_key_for_menus) do
  %label.show-menu{:for => "show-menu"} Show Menu
  %input#show-menu{:role => "button", :type => "checkbox"}
    %nav
      %ul.menu
        %li= link_to t(:home_nav), root_path, :remote => true
        %li= link_to t(:about_nav), about_path, :remote => true
        - Menu.find_each do |menu|
          - cache(menu) do
            - if menu.visible?
              %li
                = link_to menu.title, '#'
                %ul.submenu
                  - menu.categories.each do |category|
                    %li= link_to category.name, category_path(category), :remote => true

app/views/shared/_notifications.html.haml
- if current_user && !current_user.mailbox.notifications.unread.blank? && controller_name != 'messages'
  toastr.clear()
  toastr.options = {
  "closeButton": false,
  "debug": false,
  "newestOnTop": true,
  "progressBar": false,
  "positionClass": "toast-top-right",
  "preventDuplicates": false,
  "showDuration": "5000",
  "hideDuration": "1000",
  "timeOut": "60000",
  "extendedTimeOut": "1000",
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "slideDown",
  "hideMethod": "fadeOut",
  }
  - if current_user.mailbox.notifications.unread.count > 3
    toastr['info']('#{t(:noti_many_events_body).html_safe}', '#{t(:noti_many_events)}',
    {onclick: function() {$.ajax({url: '#{messages_path}', type: 'get', dataType: 'script', success: console.log('moved') })}}
    );
  - else
    - current_user.mailbox.notifications.unread.each do |noti|
      toastr['info']('#{noti.body.html_safe}', '#{noti.subject}',
      {onclick: function() {$.ajax({url: '#{message_path(noti.id)}', type: 'delete', dataType: 'script', success: console.log('deleted') })}}
      );
- if !flash.empty?
  toastr.options = {
  "closeButton": false,
  "debug": false,
  "newestOnTop": true,
  "progressBar": false,
  "positionClass": "toast-top-right",
  "preventDuplicates": false,
  "showDuration": "5000",
  "hideDuration": "1000",
  "timeOut": "7000",
  "extendedTimeOut": "1000",
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "slideDown",
  "hideMethod": "fadeOut",
  }
  - flash.each do |name, msg|
    toastr['#{name}']('#{msg}')
  - flash.clear